plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.5' apply false
    id 'net.kyori.blossom' version '2.1.0' apply false
    id 'fabric-loom' version '1.14-SNAPSHOT' apply false
}

subprojects {
    apply plugin: 'java'

    group = project.project_group
    version = project.project_version

    repositories {
        mavenCentral()
        maven {
            name = "PaperMC"
            url = "https://repo.papermc.io/repository/maven-public/"
        }
        maven {
            name = "CodeMC"
            url = "https://repo.codemc.io/repository/maven-public/"
        }
        maven {
            name = "PlaceholderAPI"
            url = "https://repo.extendedclip.com/content/repositories/placeholderapi/"
        }
        maven {
            name = "Jitpack"
            url = "https://jitpack.io"
        }
        maven {
            name = "Bungeecord"
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
    }

    dependencies {
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release.set(21)
        options.fork = true
        options.compilerArgs.add("-XDstringConcat=inline")
    }
}
