plugins {
    id 'base'
}

group = 'team.avion'
version = project.hasProperty('VERSION') ? project.VERSION : '0.1.0-SNAPSHOT'
description = 'Plugin that adds support for using VoiceCraft on Java servers.'

ext {
    pluginName = 'GeyserVoice'
    pluginUrl = 'https://geyservoice.avion.team'
    pluginAuthor = 'lil-jon-crunk'
    javaTarget = JavaVersion.VERSION_21
    voiceCraft = [
        githubRepository   : 'AvionBlock/VoiceCraft',
        release            : 'latest',
        installDirectory   : 'voicecraft-runtime',
        executableBaseName : 'VoiceCraft.Server',
        protocolMajor      : 1,
        protocolMinor      : 6,
        protocolPatch      : 0
    ]
}

allprojects {
    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
        maven {
            name = "PaperMC"
            url = uri("https://repo.papermc.io/repository/maven-public/")
        }
        maven {
            name = "PlaceholderAPI"
            url = uri("https://repo.extendedclip.com/releases/")
        }
        maven {
            name = "Bungeecord"
            url = uri("https://oss.sonatype.org/content/repositories/snapshots")
        }
    }
}

subprojects {
    apply plugin: 'java-library'

    java {
        sourceCompatibility = rootProject.ext.javaTarget
        targetCompatibility = rootProject.ext.javaTarget
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
        options.charSet = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        systemProperty 'file.encoding', 'UTF-8'
    }
}
