# Project
project_group=io.greitan
project_version=1.0.0
description=Plugin that adds support for using VoiceCraft on Java servers.

# Minecraft / Fabric
minecraft_version=1.21.10
fabric_loader_version=0.18.1
fabric_api_version=0.135.0+1.21.10
yarn_mappings=1.21.10+build.1:v2

# Platforms
paper_version=1.21.10-R0.1-SNAPSHOT
velocity_version=3.4.0-SNAPSHOT
bungeecord_version=1.21-R0.5

# Libs
lombok_version=1.18.34
jackson_version=2.18.1
blossom_version=2.1.0
shadow_version=8.1.8
