rootProject.name = 'GeyserVoice'
include 'core'
include 'paper'
include 'velocity'
include 'bungeecord'

project(':core').projectDir = file('modules/core')
project(':paper').projectDir = file('modules/paper')
project(':velocity').projectDir = file('modules/velocity')
project(':bungeecord').projectDir = file('modules/bungeecord')
