config:
  debug: false # Включить дополнительное логирование
  lang: "system" # system, en, ru, nl, ja
  auto-reconnect: true # Переподключаться к VoiceCraft после потери соединения

  voicecraft:
    transport:
      host: "127.0.0.1" # TCP-хост VoiceCraft
      port: 9050 # TCP-порт VoiceCraft
      login-token: "__GENERATED_LOGIN_TOKEN__" # LoginToken сервера VoiceCraft
    voice:
      port: 1111 # Порт голосового сервера VoiceCraft

  voice:
    proximity-distance: 30 # Максимальная дистанция голоса
    proximity-toggle: true # Включить обработку proximity
    voice-effects: true # Включить эффекты пещеры и воды

    send-bind-message: true # Show a message when a player links to VoiceCraft
    send-disconnect-message: true # Show a message when a player leaves voice chat
    send-voicecraft-disconnect-message: true # Show a message when the VoiceCraft connection closes
    send-connection-lost-message: true # Show a message when the VoiceCraft connection is lost
    position-update-interval-ticks: 5 # Интервал обновления позиций в тиках
