plugins {
    id 'java-library'
    id 'com.gradleup.shadow'
}

dependencies {
    api("com.fasterxml.jackson.core:jackson-databind:${project.jackson_version}")
    compileOnly "me.clip:placeholderapi:2.11.6"
    compileOnly "net.kyori:adventure-api:4.17.0"
}

shadowJar {
    archiveClassifier.set("common")
}
