plugins {
    id 'io.github.goooler.shadow'
}

dependencies {
    implementation project(':common')
    compileOnly "io.papermc.paper:paper-api:${project.paper_version}"
    compileOnly "me.clip:placeholderapi:2.11.6"
}

shadowJar {
    archiveClassifier.set('')
    relocate 'io.greitan.avion.common', 'io.greitan.avion.paper.common'
    configurations = [project.configurations.runtimeClasspath]
}

blossom {
    replaceToken '{{ version }}', project.version
    replaceToken '{{ description }}', project.description
    replaceToken '{{ name }}', rootProject.name
    replaceToken '{{ url }}', 'https://uninode.de'
}
