plugins {
    id 'com.gradleup.shadow'
}

dependencies {
    implementation project(':common')
    compileOnly "com.velocitypowered:velocity-api:${project.velocity_version}"
    annotationProcessor "com.velocitypowered:velocity-api:${project.velocity_version}"
    compileOnly "org.projectlombok:lombok:${project.lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${project.lombok_version}"
    
    implementation "com.github.simplix-softworks:SimplixStorage:3.2.6"
    implementation "net.md-5:bungeecord-chat:1.16-R0.4"
}

shadowJar {
    archiveClassifier.set('')
    // relocate 'io.greitan.avion.common', 'io.greitan.avion.velocity.common'
}

jar {
    archiveClassifier.set('unshaded')
}
