name: Build and Archive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geyser-voice-artifacts
          path: |
            modules/paper/build/libs/
            modules/velocity/build/libs/
            modules/bungeecord/build/libs/
